# Generated by Django 3.1.1 on 2021-01-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lang_code',
            field=models.CharField(default='en', max_length=2),
            preserve_default=False,
        ),
    ]
